#!/system/bin/sh
akirasuper=/data/adb/modules/selinux
bin=$akirasuper/system/bin
postfs=$akirasuper/post-fs-data.sh
props=$akirasuper/module.prop
selinux=`getenforce`

R='\e[01;91m' > /dev/null 2>&1;
G='\e[01;92m' > /dev/null 2>&1;
Y='\e[01;93m' > /dev/null 2>&1;
B='\e[01;94m' > /dev/null 2>&1;
P='\e[01;95m' > /dev/null 2>&1;
C='\e[01;96m' > /dev/null 2>&1;
N='\e[0m' > /dev/null 2>&1;

clear;
echo ""
if [ "$selinux" == "1" ]; then
    echo $Y"SELinux Status :$G Enforcing"$N
elif [ "$selinux" == "0" ]; then
    echo $Y"SELinux Status :$R Permissive"$N
fi
echo ""
echo $P"Security-Enhanced Linux (SELinux)"
echo "is a Linux kernel security module that provides a mechanism for supporting"
echo "access control security policies, including mandatory access controls (MAC)."$N
echo ""
echo -n $C" Change SELinux Mode?
[$G Enforcing = 1 $C|$R Permissive = 2 $C]: "$N
read option
if [ $option -eq 1 ]; then
      sed -i '/setenforce 0/s/.*/setenforce/' $postfs;
      sed -i "s/echo 0/echo/g" $postfs;
      sed -i '/setenforce/s/.*/setenforce 1/' $postfs;
      sed -i "s/echo/echo 1/g" $postfs;
      sed -i "s/Magisk Module providing basic SELinux Managment functionality. Security-Enhanced Linux Mode: Permissive/Magisk Module providing basic SELinux Managment functionality. Security-Enhanced Linux Mode: Enforcing/g" $props;
      echo -n $G".........---ENFORCING---.........."$N;
sleep 2
elif [ $option -eq 2 ]; then
      sed -i '/setenforce 1/s/.*/setenforce/' $postfs;
      sed -i "s/echo 1/echo/g" $postfs;
      sed -i '/setenforce/s/.*/setenforce 0/' $postfs;
      sed -i "s/echo/echo 0/g" $postfs;
      sed -i "s/Magisk Module providing basic SELinux Managment functionality. Security-Enhanced Linux Mode: Enforcing/Magisk Module providing basic SELinux Managment functionality. Security-Enhanced Linux Mode: Permissive/g" $props;
      echo -n $R".........---PERMISSIVE---.........."$N;
sleep 2
else
clear;
echo $R" Invalid Option"$N;
echo $R" Enter correct input and try again.$N";
sleep 2
sh $bin/akirasuper
fi
echo ""
echo $C"$Exiting Menu"$N;
echo $C"Good Bye.."$N;
echo ""
sleep 0.2
exit
