#!/system/bin/sh
akirasuper=/data/adb/modules/selinux
bin=$akirasuper/system/bin
postfs=$akirasuper/post-fs-data.sh

R='\e[01;91m' > /dev/null 2>&1;
G='\e[01;92m' > /dev/null 2>&1;
Y='\e[01;93m' > /dev/null 2>&1;
B='\e[01;94m' > /dev/null 2>&1;
P='\e[01;95m' > /dev/null 2>&1;
C='\e[01;96m' > /dev/null 2>&1;
N='\e[0m' > /dev/null 2>&1;

clear;
echo ""
echo $G"Current : `getenforce`"$N
echo ""
echo $P"Security-Enhanced Linux (SELinux)"
echo "is a Linux kernel security module that provides a mechanism for supporting"
echo "access control security policies, including mandatory access controls (MAC)."$N
echo ""
echo -n $C" Change SELinux Status?
[$G Enforcing = 1 $C|$R Permissive = 2 $C]: "$N
read option
if [ $option -eq 1 ]; then
      sed -i '/setenforce 0/s/.*/setenforce/' $postfs;
      sed -i "s/echo 0/echo/g" $postfs;
      sed -i '/setenforce/s/.*/setenforce 1/' $postfs;
      sed -i "s/echo/echo 1/g" $postfs;
      echo -n $G".........---ENFORCING---.........."$N
sleep 2
elif [ $option -eq 2 ]; then
      sed -i '/setenforce 1/s/.*/setenforce/' $postfs;
      sed -i "s/echo 1/echo/g" $postfs;
      sed -i '/setenforce/s/.*/setenforce 0/' $postfs;
      sed -i "s/echo/echo 0/g" $postfs;
      echo -n $G".........---PERMISSIVE---.........."$N
sleep 2
else
clear;
echo $R" Invalid Option"$N;
echo $R" Enter correct input and try again.$N";
sleep 2
sh $bin/akirasuper
fi
echo $C"Exiting Menu";
echo "Good Bye.."$N;
echo ""
sleep 0.2
exit ;;
